type ZipCodeResult {
    resultStatus: String,
    zip5: String,
    defaultCity: String,
    defaultState: String,
    defaultRecordType: String
}

type WeatherWeather {
    main: String,
    description: String
}

type WeatherMain {
    temp: Float,
    pressure: Float,
    humidity: Float,
    temp_min: Float,
    temp_max: Float
}

type WeatherSys {
    country: String,
    sunrise: Int,
    sunset: Int
}

scalar WeatherWind
scalar WeatherClouds
scalar WeatherPercip
scalar WeatherCord

type WeatherResult { 
    coord: WeatherCord,
    weather: [ WeatherWeather ],
    main: WeatherMain,
    visibility: Int,
    wind: WeatherWind,
    rain: WeatherPercip,
    snow: WeatherPercip,
    clouds: WeatherClouds,
    dt: Int,
    sys: WeatherSys,
    name: String
}


type RepresentativesResult {
    name: String,
    party: String,
    state: String,
    district: String,
    phone: String,
    office: String,
    link: String
}

type ResultSet {
    usps: ZipCodeResult,
    weather: WeatherResult
    reps: [RepresentativesResult]
}

type Query {
    lookup(zipcode: String): ResultSet
}
