query{
  lookup(zipcode: "08901"){
    usps{
      zip5,
      defaultCity,
      defaultState
    }
    weather{
      coord,
      weather{
        main,
        description
      },
      main {
        temp
        pressure
        humidity
        temp_min
        temp_max
      },
      visibility,
      wind,
      rain,
      snow,
      clouds,
			dt,
      sys{
        country,
        sunrise
        sunset
      },
      name
    },
    reps {
        name
        party
        state
        district
        phone
        office
        link
    }
  }
}